version: '3.0'

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=student
    ports:
      - "5432:5432"
